EcommerceWithDjango/urls.py
from django.contrib import admin
from django.urls import path, include

# To Show Media File
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ShopApp.urls')),
    path('account/', include('LoginApp.urls')),
    path('shop/', include('OrderApp.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

OrderApp/urls.py
from django.urls import path
from OrderApp import views

app_name = 'order_app'

urlpatterns = [
    path('add/<pk>/', view=views.add_to_cart, name='add'),
    path('cart/', view=views.cart_view, name='cart'),
]

ShopApp/urls.py
from django.urls import path
from . import views

app_name = 'shop_app'

urlpatterns = [
    path('', view=views.home.as_view(), name='home' ),
    path('product/<pk>/', view=views.ProductDetail.as_view(), name='product' ),
]

ShopApp/models.py
from django.db import models


class Category(models.Model):
    title = models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.title
    
    class Meta:
        verbose_name_plural = "Categories"
    

class Product(models.Model):
    main_image = models.ImageField(upload_to='Products')
    name = models.CharField(max_length=264)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category')
    preview_text = models.TextField(max_length=200, verbose_name='Preview Text')
    detail_text = models.TextField(max_length=1000, verbose_name='Description')
    price = models.FloatField()
    old_price = models.FloatField(default=0.0)
    created = models.DateField(auto_now_add=True)
   
    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['-created']
        

ShopApp/views.py
from django.shortcuts import render

# Import Views
from django.views.generic import ListView, DetailView 

# Import Models
from .models import Product

#Mixin
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.
class home(ListView):
    model = Product
    template_name = 'ShopApp/home.html'
    

class ProductDetail(LoginRequiredMixin, DetailView):
    model = Product
    template_name = 'ShopApp/product.html'

templates/ShopApp/home.html
{% extends 'base.html' %}
{% block title_block %}
  Home
{% endblock %}

{% block body_block %}
  <div class="container">
    <div class="row p-4 border border-1 rounded rounded-1 mb-3">
      <h3 class=" mb-3 fs-4">Feature Products</h3>
      {% for product in object_list %}
        <div class="col-md-4 col-sm-12 col-lg-3">
          <div class="card" style="height: 330px;">
            <img src="/media/{{ product.main_image }}" class="card-img-top m-0 p-0" alt="..." height="220 px" width="100%" />
            <div class="card-body">
              <h6 class="card-title"><a href="{% url 'shop_app:product' pk=product.pk %}" class="text text-decoration-none">{{ product.name }}</a></h6>
              <p class="card-text m-0">
                &#2547;{{ product.price }}&nbsp;&nbsp; <span class="text-danger old_price"><strike>&#2547;{{ product.old_price }}</strike></span>
              </p>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

templates/ShopApp/product.html
{% extends "base.html" %}

{% block title_block %}{{object.name}}{% endblock title_block %}
{% block body_block %}
    <div class="container">
        <div class="row shadow shadow-sm mt-3">
            <div class="col-md-6 col-lg-6 col-sm-12  ps-0">
                <div class="image-section">
                    <img src="/media/{{object.main_image}}" class="img-fluid p-3 border border-1 m-0" style="height: auto; width: 100%;" alt="">
                </div>
            </div>
            
            <div class="col-md-6 col-lg-6 col-sm-12">
                <div class="detail_section">
                    <h5>{{object.name}}</h5>
                    <p>&#2547;{{object.price}} <span class="text-danger">&nbsp;&nbsp;<strike>&#2547;{{object.old_price}}</strike></span></p>
                    <p>{{object.preview_text|linebreaks }}</p>
                </div>
                <a href="{% url 'order_app:add' pk=object.pk %}" class="btn btn-outline-primary">ADD TO CART</a>
            </div>

        </div>

        <div class="row">
            <div class="col-md-6 col-lg-6 col-sm-12">
                <p class="text-justify">{{object.detail_text |linebreaks}}</p>
            </div>
        </div>
    </div>
{% endblock body_block %}