EcommerceWithDjango/urls.py
from django.contrib import admin
from django.urls import path, include

# To Show Media File
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ShopApp.urls')),
    path('account/', include('LoginApp.urls')),
    path('shop/', include('OrderApp.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LoginApp/urls.py
from django.urls import path
from . import views
app_name = 'login_app'

urlpatterns = [
    path('signup/',view=views.sign_up, name='signup'),
    path('login/',view=views.login_user, name='login'),
    path('logout/',view=views.logout_user, name='logout'),
    path('profile/', view= views.user_profile, name='profile'),
]

ShopApp/urls.py
from django.urls import path
from . import views

app_name = 'shop_app'

urlpatterns = [
    path('', view=views.home.as_view(), name='home' ),
    path('product/<pk>/', view=views.ProductDetail.as_view(), name='product' ),
]

LoginApp/models.py
from django.db import models

#To Create Custom User Model and Admin Panel
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin
from django.utils.translation import gettext_lazy


# To automatically create one to one objects 
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.

class MyUserManager(BaseUserManager):
    """ A custom manager to deal with emails as unique identifier """
    
    def _create_user(self, email, password, **extra_fields):
        """Creates and saves a user with given and password"""
        
        if not email:
            raise ValueError("The Email is Must be set")
        
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        
        return user    
    
    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)
        
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True')
        
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True')
        return self._create_user(email, password, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True, null=False)
    
    is_staff = models.BooleanField(
        gettext_lazy('staff status'),
        default=False,
        help_text= gettext_lazy('Designates whether the user can log in this site')
    )
    
    is_active = models.BooleanField(
        gettext_lazy("active"),
        default=True,
        help_text=gettext_lazy("Designates Whether this user should be treated as active. Unselect this instead of deleting accounts")
    )
    
    USERNAME_FIELD = 'email'
    objects = MyUserManager()
    
    def __str__(self):
        return self.email

    def get_full_name(self):
        return self.email
    
    def get_short_name(self):
        return self.email
    
    
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    username = models.CharField(max_length=264, blank=True)
    full_name = models.CharField(max_length=264, blank=True)
    address_1 = models.TextField(max_length=300, blank=True)
    city = models.CharField(max_length=50, blank=True)
    zip_code = models.CharField(max_length=10, blank=True)
    country = models.CharField(max_length=50, blank=True)
    phone = models.CharField(max_length=20, blank=True)
    date_joined = models.DateTimeField(auto_now_add=True)
    
    
    def __str__(self):
        return self.user.email + "'s Profile"
    
    def is_fully_filled(self):
        fields_name = [f.name for f in self._meta.get_field()]
        
        for field_name in fields_name:
            value = getattr(self, field_name)
            
            if value is None or value=='':
                return False
            
        return True
    

@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_profile(sender, instance, **kwargs):
    instance.profile.save()

LoginApp/forms.py
from django.forms import ModelForm
from .models import User, Profile

from django.contrib.auth.forms import UserCreationForm

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        exclude = ('user',)

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email','password1', 'password2')        

LoginApp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

# Authentication form
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout, authenticate

# forms and model
from .forms import ProfileForm, SignUpForm
from .models import Profile, User

# message
from django.contrib import messages


# Create your views here.
def sign_up(request):
    form =  SignUpForm()
    
    if request.method == "POST":
        form = SignUpForm(request.POST)
        
        if form.is_valid():
            form.save()
            messages.success(request, "Account Created Successfully")
            return redirect('login_app:login')
   
    return render(request, 'LoginApp/signup.html', context={'form':form})
    

def login_user(request):
    form = AuthenticationForm()
    
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            
            user = authenticate(username=username, password=password)
            
            if user is not None:
                login(request,user)
                return redirect("shop_app:home")
            else:
                return HttpResponse("Email and password not found")
    
    return render(request, 'LoginApp/login.html', context={'form':form})

@login_required
def logout_user(request):
    logout(request)
    messages.warning(request, "Your are logged out")
    return redirect("shop_app:home")

@login_required
def user_profile(request):
    profile = Profile.objects.get(user=request.user)
    form = ProfileForm(instance=profile)
    
    if request.method == "POST":
        form = ProfileForm(request.POST, instance=profile)
        
        if form.is_valid():
            form.save()
            messages.success(request, "Saved Successfully")
            form = ProfileForm(instance=profile)
    
    return render(request, 'LoginApp/change_profile.html', context={'form':form})

templates/LoginApp/change_profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title_block %}Profile{% endblock title_block %}

{% block body_block %}
        <div class="row">
            <div class="col-4 m-auto mt-2 p-3 border border-2 rounded">
                <h2 class="text-center">Profile</h2>
                <form method="POST">
                    {% csrf_token %}
                    {{form | crispy}}
                    <div class="d-flex justify-content-center">
                        <input type="submit" value="Update" class="btn btn-dark btn-sm">
                    </div>
                </form>
            </div>
        </div>
{% endblock body_block %}

templates/LoginApp/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title_block %}Sign In{% endblock title_block %}

{% block body_block %}
        <div class="row">
            <div class="col-4 m-auto mt-2 p-3 border border-2 rounded">
                <h2 class="text-center">Login</h2>
                <form method="POST">
                    {% csrf_token %}
                    {{form | crispy}}
                    <div class="d-flex justify-content-center">
                        <input type="submit" value="Sign In" class="btn btn-dark btn-sm">
                    </div>
                    <p class="d-block text-center mt-2 have_account">Don't Have an Account?<a href="{% url "login_app:signup" %}"> Click Here</a></p>
                </form>
            </div>
        </div>
{% endblock body_block %}

templates/LoginApp/signup.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title_block %}Sign Up{% endblock title_block %}

{% block body_block %}
        <div class="row">
            <div class="col-4 m-auto mt-2 p-3 border border-2 rounded">
                <h2 class="text-center">Sign Up</h2>
                <form method="POST">
                    {% csrf_token %}
                    {{form | crispy}}
                    <div class="d-flex justify-content-center">
                        <input type="submit" value="Sign Up" class="btn btn-dark btn-sm">
                    </div>
                    <p class="d-block text-center mt-2 have_account">Already Have an Account?<a href="{% url "login_app:login" %}"> Click Here</a></p>
                </form>
            </div>
        </div>
{% endblock body_block %}