EcommerceWithDjango/urls.py
from django.contrib import admin
from django.urls import path, include

# To Show Media File
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ShopApp.urls')),
    path('account/', include('LoginApp.urls')),
    path('shop/', include('OrderApp.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LoginApp/urls.py
from django.urls import path
from . import views
app_name = 'login_app'

urlpatterns = [
    path('signup/',view=views.sign_up, name='signup'),
    path('login/',view=views.login_user, name='login'),
    path('logout/',view=views.logout_user, name='logout'),
    path('profile/', view= views.user_profile, name='profile'),
]

OrderApp/urls.py
from django.urls import path
from OrderApp import views

app_name = 'order_app'

urlpatterns = [
    path('add/<pk>/', view=views.add_to_cart, name='add'),
    path('cart/', view=views.cart_view, name='cart'),
]

ShopApp/urls.py
from django.urls import path
from . import views

app_name = 'shop_app'

urlpatterns = [
    path('', view=views.home.as_view(), name='home' ),
    path('product/<pk>/', view=views.ProductDetail.as_view(), name='product' ),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css"/>
    <link href="https://fonts.googleapis.com/css2?family=Monoton&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    <title>{% block title_block %}{% endblock title_block %}</title>
</head>
<body>
   {% include "navbar.html" %}
    <div class="container">
        <div class="row">
            <div class="col-4 m-auto  mt-2">
                {% for message in messages  %}
                 <div {% if message.tags %} class="alert alert-{{message.tags}}"{% endif %} role="alert">
                    {{message}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                 </div>
            {% endfor %}
            </div>
        </div>
         {% block body_block %}{% endblock body_block %}
    </div>

    <script>
        // Auto-dismiss Bootstrap alerts after 5 seconds (5000ms)
        setTimeout(function() {
            let alerts = document.querySelectorAll(".alert");
            alerts.forEach(function(alert) {
                let bsAlert = new bootstrap.Alert(alert);
                bsAlert.close();
            });
        }, 3000);
    </script>
    

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.slim.js"></script>
</body>
</html>

templates/navbar.html
{% load cart_tag %}
<nav class="navbar navbar-expand-lg" data-bs-theme="dark" style="background-color: blueviolet;">
  <div class="container">
    <a class="navbar-brand logo" href="{% url 'shop_app:home' %}">Ecommerce</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ms-auto">
        {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" style="color: white;" href="{% url 'order_app:cart' %}">
              <i class="fa-solid fa-cart-shopping"></i> Cart<span class="badge badge-light"><sup>{{request.user | cart_total }}</sup></span>
            </a>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" style="color: white;" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fa-solid fa-user-tie"></i> {{ request.user.profile.username }}</a>
            <ul class="dropdown-menu">
              <li>
                <a class="dropdown-item" href="{% url 'login_app:profile' %}">Profile</a>
              </li>

              <li>
                <a class="dropdown-item" href="#">Order</a>
              </li>

              <div class="dropdown-divider"></div>
              <li>
                <a class="dropdown-item" href="{% url 'login_app:logout' %}">Logout</a>
              </li>
            </ul>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="btn btn-light btn-sm" href="{% url 'login_app:login' %}">Login</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>